#!/usr/bin/env python3
"""Write reports/STATUS.md from the ARTIFACT. Never hand-edited.

A status file typed by hand is a claim; this one is a measurement, and it is
regenerated by the same run that gates the build.
"""
from __future__ import annotations

import collections
import glob
import io
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import binding as binding_mod
import itemio
import run_gates

OUT = os.path.join(itemio.BANK_ROOT, "reports", "STATUS.md")


def main():
    b = binding_mod.load()
    items = itemio.load_dir(b.output_dir)
    quar = itemio.load_dir(b.quarantine_dir)

    _, results = run_gates.collect(b)
    failed = [r for r in results if not (r.passed and r.measured)]

    live = [i for i in items if itemio.servable(i)]
    covered = {c for i in live for c in i["standardCodes"]}
    allc = b.valid_codes()
    qreason = collections.Counter(
        "tests an element the 2027-28 standard dropped"
        if ((i.get("provenance") or {}).get("alignmentReview") or {}).get("droppedElementsTested")
        else "standard retired / no 2027-28 home" for i in quar)

    L = []
    L.append("# Status — US History and Geography item bank\n")
    L.append("**HELD.** Not Grade A. This file is a measurement of the built artifact, "
             "regenerated by `tools/status_report.py`; it is never hand-edited.\n")
    L.append(f"```\n{b.declaration()}\n```\n")
    L.append("## Gates\n\n| Gate | Result | Scanned | Judged | Findings |\n|---|---|---|---|---|")
    for r in results:
        L.append(f"| `{r.gate}` | **{r.status}** | {r.scanned} | "
                 f"{r.judged if r.judged is not None else '—'} | {len(r.findings)} |")
    L.append(f"\n**{len(results) - len(failed)}/{len(results)} pass.** "
             f'Grade A requires all of them. "Close" is not "A."\n')
    L.append("## Bank\n")
    L.append(f"- Source: **5,045** items from the 2026-27 `history-hack-web-app` bank")
    L.append(f"- Servable: **{len(live)}** "
             f"({sum(1 for i in live if i['status']=='migrated')} migrated, "
             f"{sum(1 for i in live if i['status']=='provisional')} provisional)")
    L.append(f"- Quarantined (not servable, not coverage): **{len(quar)}**")
    for k, v in qreason.most_common():
        L.append(f"  - {v} — {k}")
    L.append(f"- Standards with a servable item: **{len(covered)}/{len(allc)}**")
    L.append(f"- Standards receiving nothing: **{len(allc - covered)}** — "
             + ", ".join(sorted(allc - covered)) + "\n")

    forms = sorted(d for d in glob.glob(os.path.join(itemio.BANK_ROOT, "forms", "*"))
                   if os.path.isdir(d))
    L.append("## Forms\n")
    if not forms:
        L.append("None built.\n")
    for fd in forms:
        m = json.load(open(os.path.join(fd, "manifest.json"), encoding="utf-8"))
        L.append(f"- **{m['formId']}** — {m['itemCount']} items across "
                 f"{len(m['standards'])} standard(s): {', '.join(m['standards'])}"
                 + (f"  \n  SHORT of blueprint: {m['shortOfBlueprint']}"
                    if m["shortOfBlueprint"] else ""))
    L.append("")
    L.append("## Authoring debt\n\n| Gap | Count |\n|---|---|")
    for k, v in [
        ("distractor rationales absent",
         sum(1 for i in live for c in itemio.choices(i)
             if c.get("id") != i.get("correctAnswer") and not (c.get("explanation") or "").strip())),
        ("items with no dokRationale",
         sum(1 for i in live if not (i.get("dokRationale") or "").strip())),
        ("items with no stemEs", sum(1 for i in live if not (i.get("stemEs") or "").strip())),
        ("items with no explanationEs",
         sum(1 for i in live if not (i.get("explanationEs") or "").strip())),
        ("standards with no reporting-category source", len(allc)),
    ]:
        L.append(f"| {k} | {v} |")
    L.append("")
    L.append(open(os.path.join(itemio.BANK_ROOT, "reports", "_decisions.md"),
                  encoding="utf-8").read())

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print(f"wrote {os.path.relpath(OUT, itemio.BANK_ROOT)} — "
          f"{len(results) - len(failed)}/{len(results)} gates pass")
    # A report generator's exit code describes GENERATION, not its subject. This
    # once exited non-zero because the bank had failing gates, which made the
    # pipeline report the same failure twice and made a real generator crash
    # indistinguishable from a bank that simply is not finished yet.
    return 0


if __name__ == "__main__":
    sys.exit(main())
